export const GET_COMMENTS = 'GET_COMMENTS';
export const GET_COMMENTS_PENDING = 'GET_COMMENTS_PENDING';
export const GET_COMMENTS_FULFILLED = 'GET_COMMENTS_FULFILLED';
export const GET_COMMENTS_REJECTED = 'GET_COMMENTS_REJECTED';
export const ADD_COMMENT = 'ADD_COMMENT';
export const EDIT_COMMENT = 'EDIT_COMMENT';
export const DEL_COMMENT = 'DEL_COMMENT';